name: myned
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # --- අලුතින් එක් කළ Packages ---
  get: ^4.6.6              # State management සහ Navigation සඳහා
  google_fonts: ^6.2.1     # ලස්සන Fonts පාවිච්චි කරන්න

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true