// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQoAUHzo7JtwvKFWwGTLrLYp5YnSCZaI4',
    appId: '1:749838147100:web:86e5f074eb41f2966cc9d9',
    messagingSenderId: '749838147100',
    projectId: 'myned-finance',
    authDomain: 'myned-finance.firebaseapp.com',
    storageBucket: 'myned-finance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHg_CGhpR37RdisC2mjfhfnViZrF4y9a0',
    appId: '1:749838147100:android:257644beb8178c5d6cc9d9',
    messagingSenderId: '749838147100',
    projectId: 'myned-finance',
    storageBucket: 'myned-finance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALy5q2SX53cjPDU6MEFf5Soj5DhOiaN00',
    appId: '1:749838147100:ios:5df7e8d37b2c1ac86cc9d9',
    messagingSenderId: '749838147100',
    projectId: 'myned-finance',
    storageBucket: 'myned-finance.firebasestorage.app',
    iosBundleId: 'com.myned.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALy5q2SX53cjPDU6MEFf5Soj5DhOiaN00',
    appId: '1:749838147100:ios:dea22405fee874596cc9d9',
    messagingSenderId: '749838147100',
    projectId: 'myned-finance',
    storageBucket: 'myned-finance.firebasestorage.app',
    iosBundleId: 'com.myned.finance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQoAUHzo7JtwvKFWwGTLrLYp5YnSCZaI4',
    appId: '1:749838147100:web:566cf7b4b3dbd3936cc9d9',
    messagingSenderId: '749838147100',
    projectId: 'myned-finance',
    authDomain: 'myned-finance.firebaseapp.com',
    storageBucket: 'myned-finance.firebasestorage.app',
  );

}